### ISSUE TITLE
Upgrading from v0.x to v1.0 docs

### ISSUE THREAD

**Issue by dawzrd** [tailwindcss/docs#211]
You may want to mention in your 1.0 upgrade guide that all color names have changed. In the examples throughout the docs, colors are using the non-numeric-suffixed-old-legacy-name.

Its not until [https://tailwindcss.com/docs/customizing-colors/#naming-your-colors](https://tailwindcss.com/docs/customizing-colors/#naming-your-colors)

that we finally find out why all of our colors are missing.

**Comment by dawzrd** [comment]
@adamwathan , I am a dev just using vanilla straight out the box tailwind, (I love the thing btw).

I just think, if you came at it(the docs) from a Tailwind is my starting point it may offer a different perspective.

**Comment by adamwathan** [comment]
Closing this because not sure what we could really do differently, the upgrade guide is accurate and walks you through how to upgrade your config file and preserve all your existing color classes, it's only if you don't have a config file that it matters and even that's documented in the upgrade guide.
