### ISSUE TITLE
Mistake in docs

### ISSUE THREAD

**Issue by yantakus** [tailwindcss/docs#223]
In [this](https://tailwindcss.com/docs/upgrading-to-v1/#12-explicitly-add-color-and-underline-styles-to-links) section of upgrade guide it says to add `text-blue` class to links, but there's no `text-blue` class anymore, just `text-blue-{number}`.

**Comment by adamwathan** [comment]
There would still be a `text-blue` class if you were upgrading an existing project, because the upgrade process outlined in the upgrade guide preserves all of your old colors.

It's not until [this step](https://tailwindcss.com/docs/upgrading-to-v1/#1-update-any-usage-of-text-bg-border-color-classes) towards the end of the upgrade guide that we explain how to update your color names if you want to do that. Sort of confusing admittedly, not sure the best way to avoid that confusion.

Personally I think if you are upgrading a Tailwind 0.x project and you used the old default colors, you should keep using the old default colors after upgrading because otherwise your site is going to look different, and you'll have to update tons and tons of classes in your HTML.

**Comment by yantakus** [comment]
Thanks for the explanation. I'm upgrading, but I don't keep the old colors (because I didn't modify them). So it's missing for me. That's why I decided to post the issue.
