### ISSUE TITLE
[Docs] Wrong dependency location for PurgeCSS package  

### ISSUE THREAD

**Issue by thomlom** [tailwindcss/docs#241]
While [setting up Purgecss](https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss) in my app, I noticed the docs say to install PurgeCSS that way: 

```
# Using npm
npm install @fullhuman/postcss-purgecss

# Using yarn
yarn add @fullhuman/postcss-purgecss
```

If I'm not mistaken, PostCSS is part of the build process, so installing that dependency should be located in the `devDependencies` 🙂: 

```
# Using npm
npm install --save-dev @fullhuman/postcss-purgecss

# Using yarn
yarn add --dev @fullhuman/postcss-purgecss
```

**Comment by adamwathan** [comment]
Will change this although I don't think it really matters. Since you're installing it in your actual project and not in a package, you always need to install all your dependencies (including devDependencies) to build your project anyways. Tailwind itself is technically a devDependency really too since it's only used during the build process and never used at run-time.
