### ISSUE TITLE
"smart enough" to do something unexpected? What?

### ISSUE THREAD

**Issue by tremby** [tailwindcss/docs#280]
In three spots of the documentation:

- https://github.com/tailwindcss/docs/blob/af6d3df4086cf0f4d034066f3eb46006cbe71677/source/docs/z-index.blade.md#negative-values
- https://github.com/tailwindcss/docs/blob/02088cf65d923cfdb47b831496a8393ac3a5b7b9/source/docs/top-right-bottom-left.blade.md#negative-values
- https://github.com/tailwindcss/docs/blob/b7fde288884daefc6e209ac08df4335a756b0b9b/source/docs/margin.blade.md#negative-values

there are phrases like this one:

> Tailwind is smart enough to generate classes like `-z-10` when it sees the leading dash, not `z--10` like you might expect.

I agree that I would certainly expect `z--10` for "z-index: negative 10". Not "negative z-index: 10".

"Smart enough to do something you wouldn't expect" -- surely this can't be serious. Is it sarcasm? Self-deprecating humour?

Or if it's really on purpose, what's the reason?

Genuinely nonplussed.

**Comment by missmatsuko** [comment]
It probably is moving the hyphen to be consistent with the negative margin classes which are included by default:
https://tailwindcss.com/docs/margin

But I agree that sentence doesn't really make sense. Smart enough to do something unexpected? It should probably be changed to just note the format of negative classes and explain why.

**Comment by tremby** [comment]
Yes, a warning would be more appropriate than confusing self-congratulation!

**Comment by adamwathan** [comment]
Yes it's by design to be consistent with the class names from Tailwind 0.x to avoid an annoying breaking change, and because none of the other possible class names were better.

Here is one of the initial discussions:
https://github.com/tailwindcss/tailwindcss/issues/848

Here's a thread on Twitter with more conversation:
https://twitter.com/adamwathan/status/1120390649151410177

Here is the pull request that added this behavior: https://github.com/tailwindcss/tailwindcss/pull/865

> "Smart enough to do something you wouldn't expect" -- surely this can't be serious. Is it sarcasm? Self-deprecating humour?

Since the syntax for a negative margin class is something like `-mt-6` there needs to be *some way* to communicate to Tailwind in your config file that you want the `-` prefix on the class name, so "smart enough" in this case is saying "Tailwind notices the leading dash and understands you are creating a negative utility so puts the dash at the beginning of the class name since that is Tailwind's convention for negative utilities."

I'll think about a better way to surface this behavior in the docs for people seeing it from the other side, where they've added a key like `-6` with the intention of creating a class like `z--6` and seeing `-z-6` instead.

Either way your pissy attitude is not appreciated.

**Comment by tremby** [comment]
> I'll think about a better way to surface this behavior

Yes, a change to the docs is all I'm suggesting, to remove the current nonsensical statement.

Thank you for an excellent response. Until...

> Either way your pissy attitude is not appreciated.

Perhaps you got up on the wrong side of bed and misinterpreted my tone?

**Comment by adamwathan** [comment]
If you don't see how ending an issue title with "What?" and saying things like "surely this can't be serious" as if to imply "who on earth in their right mind would ever write this sentence" could be perceived as antagonistic and rude to the person who spent multiple days trying to make the right trade-offs for the behavior you're complaining about then I don't know what to tell you.

Have more grace and assume people thought things through before making decisions instead storming in and acting like there must be something wrong with the people who work on the project.
