### ISSUE TITLE
Remove anchorjs in favor of Tailwindcss for Anchor links

### ISSUE THREAD

**Issue by brennanangel** [tailwindcss/docs#466]
It looks like the Tailwindcss docs use JS to show/hide the heading anchor links. 

I believe this could be done purely with Tailwindcss (and remove anchorjs):

## Before
```html
<h2 id="enabling-all-variants">
    <a class="anchorjs-link text-gray-500 no-underline" aria-label="Anchor" data-anchorjs-icon="#" href="#enabling-all-variants" style="position: absolute; margin-left: -1em; padding-right: 0.5em;">
        <span class="text-gray-900">Enabling all variants</span>
    </a>
</h2>
```

## After
```html
<h2 id="enabling-all-variants" class="text-white no-underline hover:text-gray-500">
    <a class="cursor-default" aria-label="Anchor" href="#enabling-all-variants">
        <span class="absolute pr-3 -ml-6 text-xl cursor-pointer">#</span>
        <span class="text-gray-900">Enabling all variants</span>
    </a>
</h2>
```

FYI, the `pr-3` is there to prevent a gap in the link.

**Comment by adamwathan** [comment]
We use JS for this because the docs are authored in markdown and most of the headings are written using markdown syntax instead of raw HTML:

![image](https://user-images.githubusercontent.com/4323180/87253801-ef9f3080-c44b-11ea-8568-6060696203a4.png)

Thanks for the suggestion but not something we plan to change any time soon.
