### ISSUE TITLE
macOS: Chrome scrollbar over code snippet

### ISSUE THREAD

**Issue by tgdn** [tailwindcss/docs#80]
Does that in all one-line snippets of code which have an x-overflow:

![image](https://user-images.githubusercontent.com/480050/54275493-a94d6f00-4582-11e9-999b-f4c026743cb1.png)

A possible solution would be add a padding-bottom to each `<pre>`.

**Comment by adamwathan** [comment]
Fixed (on the `next` branch anyways, which will replace the old docs soon.) Thanks!

**Comment by munirapp** [comment]
Can you open this issue? because i got same case like this, scrollbar not show on code snippet and make hard to read all the code

![image](https://user-images.githubusercontent.com/17497888/83748036-29825780-a694-11ea-839e-d0e1deb77916.png)

OS: Mac OS Catalina 
Browser: Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by munirapp** [comment]
Note: The Scrollbar actually works (I can scroll it with touchpad gesture) but it can't be scroll if you using mouse
